batch_size: 16
height: 32
learning_rate: 0.0005
max_text_length: 16
model_path: Models/03_handwriting_recognition\202404271822
train_epochs: 1000
train_workers: 20
vocab: (h#K-id8jcAo4O)nTtYslgNm:,S&vMRZ.p"GeyFUfIQ'B7kux20L9aW3qrDC!J1HP?6zb;5VwE
width: 128
